/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.administrativo.telas;

import br.edu.imepac.administrativo.entidades.Paciente;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author elias
 */
public class CadastrarPaciente extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarConvenio
     */
    public CadastrarPaciente() {
        initComponents();
        setLocationRelativeTo(null);
    }

    CadastrarPaciente(Connection conn) {
        throw new UnsupportedOperationException("Not supported yet."); 
// Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFnome = new javax.swing.JTextField();
        JFsexo = new javax.swing.JTextField();
        JFcidade = new javax.swing.JTextField();
        nascimento = new javax.swing.JFormattedTextField();
        NomeLabel = new javax.swing.JLabel();
        LabelCodigo = new javax.swing.JLabel();
        LabelDesc = new javax.swing.JLabel();
        LabelDataInicio = new javax.swing.JLabel();
        BotãoSalvar = new javax.swing.JButton();
        BotãoLimpar = new javax.swing.JButton();
        BotãoVoltar = new javax.swing.JButton();
        AbrirListagem = new javax.swing.JButton();
        JFcpf = new javax.swing.JTextField();
        JFuf = new javax.swing.JTextField();
        JFcep = new javax.swing.JTextField();
        LabelDesc1 = new javax.swing.JLabel();
        LabelDesc2 = new javax.swing.JLabel();
        LabelDesc3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        JFnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFnomeActionPerformed(evt);
            }
        });
        getContentPane().add(JFnome);
        JFnome.setBounds(80, 70, 260, 33);
        getContentPane().add(JFsexo);
        JFsexo.setBounds(380, 70, 80, 33);
        getContentPane().add(JFcidade);
        JFcidade.setBounds(80, 190, 260, 33);

        try {
            nascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        nascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nascimentoActionPerformed(evt);
            }
        });
        getContentPane().add(nascimento);
        nascimento.setBounds(80, 250, 110, 33);

        NomeLabel.setText("Nome");
        getContentPane().add(NomeLabel);
        NomeLabel.setBounds(40, 80, 40, 16);

        LabelCodigo.setText("Sexo");
        getContentPane().add(LabelCodigo);
        LabelCodigo.setBounds(350, 80, 30, 16);

        LabelDesc.setText("Uf");
        getContentPane().add(LabelDesc);
        LabelDesc.setBounds(350, 130, 30, 16);

        LabelDataInicio.setText("Nascimento");
        getContentPane().add(LabelDataInicio);
        LabelDataInicio.setBounds(80, 230, 110, 16);

        BotãoSalvar.setText("SALVAR");
        BotãoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(BotãoSalvar);
        BotãoSalvar.setBounds(30, 300, 118, 35);

        BotãoLimpar.setText("LIMPAR");
        BotãoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoLimparActionPerformed(evt);
            }
        });
        getContentPane().add(BotãoLimpar);
        BotãoLimpar.setBounds(170, 300, 120, 35);

        BotãoVoltar.setText("Voltar");
        BotãoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BotãoVoltar);
        BotãoVoltar.setBounds(510, 10, 80, 23);

        AbrirListagem.setText("Listar Paciente");
        AbrirListagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirListagemActionPerformed(evt);
            }
        });
        getContentPane().add(AbrirListagem);
        AbrirListagem.setBounds(40, 350, 250, 40);
        getContentPane().add(JFcpf);
        JFcpf.setBounds(80, 110, 260, 33);
        getContentPane().add(JFuf);
        JFuf.setBounds(380, 120, 80, 33);
        getContentPane().add(JFcep);
        JFcep.setBounds(80, 150, 260, 33);

        LabelDesc1.setText("Cpf");
        getContentPane().add(LabelDesc1);
        LabelDesc1.setBounds(50, 120, 30, 16);

        LabelDesc2.setText("Cidade");
        getContentPane().add(LabelDesc2);
        LabelDesc2.setBounds(30, 200, 50, 16);

        LabelDesc3.setText("Cep");
        getContentPane().add(LabelDesc3);
        LabelDesc3.setBounds(50, 160, 30, 16);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("CADASTRAR PACIENTE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 20, 250, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JFnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFnomeActionPerformed

    private void BotãoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoSalvarActionPerformed
    
    try {
        // Verificar se todos os campos obrigatórios foram preenchidos
        if (JFnome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "O campo 'Nome' é obrigatório!", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (JFsexo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo 'sexo'"
                    + " é obrigatório!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (JFcpf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo 'Cpf' é obrigatório!",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        

        // Criar o objeto Convenio
        Paciente Pacientes = new Paciente();
        Pacientes.setnome(JFnome.getText());
        Pacientes.setsexo(JFsexo.getText());
        Pacientes.setsexo(JFcpf.getText());
        Pacientes.setsexo(JFuf.getText());
        Pacientes.setsexo(JFcep.getText());
        Pacientes.setsexo(JFcidade.getText());
        Pacientes.setnascimento(java.sql.Date.valueOf(nascimento.getText()));        

        // Configurações do banco de dados
        String url = "jdbc:mysql://localhost:3306"; // Substitua pelo nome do seu banco
        String user = "root"; // Substitua pelo seu usuário do MySQL
        String password = "root"; // Substitua pela sua senha do MySQL

        // Conexão e inserção no banco
        String sql = "INSERT INTO Paciente (nome, sexo,"
                + " cpf, uf, cep, cidade, nascimento) VALUES (?, ?, ?, ?, ?, ?,?)";

        try (Connection connection = DriverManager.getConnection(url, user, password);
             PreparedStatement stmt = connection.prepareStatement(sql)) {

            // Preenchendo os valores no PreparedStatement
            stmt.setString(1, Pacientes.getnome());
            stmt.setDate(2, (Date) Pacientes.getnascimento());
            stmt.setString(3, Pacientes.getsexo());
            stmt.setString(4, Pacientes.getcpf());
            stmt.setString(5, Pacientes.getcep());
            stmt.setString(6, Pacientes.getuf());           
            stmt.setString(7, Pacientes.getcidade());
          


            // Executa a inserção
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Paciente salvo com sucesso!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar no banco de dados: "
                    + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "Erro: Data de nascimento deve ser um número.", "Erro", 
                JOptionPane.ERROR_MESSAGE);
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, 
            "Erro: Certifique-se de que as datas estão no formato correto (yyyy-MM-dd).",
            "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    JOptionPane.showMessageDialog(this, "Paciente salvo com sucesso!");
    abrirListagemConvenio(); // Abre a tela de listagem

    
    }//GEN-LAST:event_BotãoSalvarActionPerformed

    private void BotãoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoVoltarActionPerformed

      // TelaLobby telaLobby = new TelaLobby(); // Instancia a próxima tela
      // telaLobby.setVisible(true); // Exibe a nova tela
      //  this.dispose(); // Fecha a tela atual (TelaLogin)
    }//GEN-LAST:event_BotãoVoltarActionPerformed

    private void nascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nascimentoActionPerformed

    private void AbrirListagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirListagemActionPerformed
        // TODO add your handling code here:
    ListagemPaciente listagempaciente = new ListagemPaciente();
    listagempaciente.setVisible(true);
    this.dispose();
    
    }//GEN-LAST:event_AbrirListagemActionPerformed

    private void BotãoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoLimparActionPerformed
        // TODO add your handling code here:
         // Limpar os campos de texto
    JFnome.setText("");
    JFsexo.setText("");
    JFcep.setText("");
    JFcpf.setText("");
    JFuf.setText("");
    JFcidade.setText("");
    nascimento.setText("");

  //  StatusConv.setSelected(false);
    }//GEN-LAST:event_BotãoLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CadastrarPaciente().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbrirListagem;
    private javax.swing.JButton BotãoLimpar;
    private javax.swing.JButton BotãoSalvar;
    private javax.swing.JButton BotãoVoltar;
    private javax.swing.JTextField JFcep;
    private javax.swing.JTextField JFcidade;
    private javax.swing.JTextField JFcpf;
    private javax.swing.JTextField JFnome;
    private javax.swing.JTextField JFsexo;
    private javax.swing.JTextField JFuf;
    private javax.swing.JLabel LabelCodigo;
    private javax.swing.JLabel LabelDataInicio;
    private javax.swing.JLabel LabelDesc;
    private javax.swing.JLabel LabelDesc1;
    private javax.swing.JLabel LabelDesc2;
    private javax.swing.JLabel LabelDesc3;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField nascimento;
    // End of variables declaration//GEN-END:variables

    private void abrirListagemConvenio() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }



}

