/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.administrativo.telas;

import br.edu.imepac.administrativo.daos.PerfilDAO;
import br.edu.imepac.administrativo.entidades.Perfil;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author elias
 */
public class CadastrarPerfil extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarPerfil
     */
    public CadastrarPerfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NomePerfilTextField = new javax.swing.JTextField();
        cadastrarFuncionarios = new javax.swing.JCheckBox();
        lerFuncionarios = new javax.swing.JCheckBox();
        listarFuncionarios = new javax.swing.JCheckBox();
        atualizarFuncionarios = new javax.swing.JCheckBox();
        deletarFuncionarios = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cadastrarPacientes = new javax.swing.JCheckBox();
        lerPacientes = new javax.swing.JCheckBox();
        listarPacientes = new javax.swing.JCheckBox();
        atualizarPacientes = new javax.swing.JCheckBox();
        deletarPacientes = new javax.swing.JCheckBox();
        deletarConsultas = new javax.swing.JCheckBox();
        lerConsultas = new javax.swing.JCheckBox();
        atualizarConsultas = new javax.swing.JCheckBox();
        cadastrarConsultas = new javax.swing.JCheckBox();
        listarConsultas = new javax.swing.JCheckBox();
        deletarEspecialidades = new javax.swing.JCheckBox();
        lerEspecialidades = new javax.swing.JCheckBox();
        cadastrarEspecialidades = new javax.swing.JCheckBox();
        listarEspecialidades = new javax.swing.JCheckBox();
        atualizarEspecialidades = new javax.swing.JCheckBox();
        atualizarConvenios = new javax.swing.JCheckBox();
        lerConvenios = new javax.swing.JCheckBox();
        cadastrarConvenios = new javax.swing.JCheckBox();
        listarConvenios = new javax.swing.JCheckBox();
        deletarConvenios = new javax.swing.JCheckBox();
        SALVAR = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BotãoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(518, 899));
        setMinimumSize(new java.awt.Dimension(518, 899));
        setPreferredSize(new java.awt.Dimension(518, 899));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Cadastrar Perfil");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 30, 190, 32);

        NomePerfilTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomePerfilTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(NomePerfilTextField);
        NomePerfilTextField.setBounds(70, 140, 380, 40);

        cadastrarFuncionarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadastrarFuncionarios.setText("Cadastrar ");
        cadastrarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncionariosActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarFuncionarios);
        cadastrarFuncionarios.setBounds(70, 230, 120, 29);

        lerFuncionarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lerFuncionarios.setText("Ler ");
        getContentPane().add(lerFuncionarios);
        lerFuncionarios.setBounds(200, 230, 60, 29);

        listarFuncionarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listarFuncionarios.setText("Listar");
        listarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarFuncionariosActionPerformed(evt);
            }
        });
        getContentPane().add(listarFuncionarios);
        listarFuncionarios.setBounds(290, 230, 80, 29);

        atualizarFuncionarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        atualizarFuncionarios.setText("Atualizar ");
        getContentPane().add(atualizarFuncionarios);
        atualizarFuncionarios.setBounds(70, 260, 96, 29);

        deletarFuncionarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deletarFuncionarios.setText("Deletar");
        deletarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarFuncionariosActionPerformed(evt);
            }
        });
        getContentPane().add(deletarFuncionarios);
        deletarFuncionarios.setBounds(200, 260, 80, 29);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Permissões relacionadas a Funcionários");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 200, 380, 25);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 80, 570, 10);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Permissões relacionadas a Pacientes");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 300, 310, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("Permissões relacionadas a Consultas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 420, 340, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("Permissões relacionadas a Especialidades");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 540, 380, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setText("Permissões relacionadas a Convênios");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 650, 350, 25);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nome do perfil");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 110, 160, 30);

        cadastrarPacientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadastrarPacientes.setText("Cadastrar ");
        cadastrarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarPacientes);
        cadastrarPacientes.setBounds(80, 340, 130, 29);

        lerPacientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lerPacientes.setText("Ler ");
        getContentPane().add(lerPacientes);
        lerPacientes.setBounds(210, 340, 60, 29);

        listarPacientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listarPacientes.setText("Listar");
        listarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(listarPacientes);
        listarPacientes.setBounds(300, 340, 80, 29);

        atualizarPacientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        atualizarPacientes.setText("Atualizar ");
        getContentPane().add(atualizarPacientes);
        atualizarPacientes.setBounds(80, 370, 96, 29);

        deletarPacientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deletarPacientes.setText("Deletar");
        deletarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(deletarPacientes);
        deletarPacientes.setBounds(210, 370, 80, 29);

        deletarConsultas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deletarConsultas.setText("Deletar");
        deletarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(deletarConsultas);
        deletarConsultas.setBounds(200, 490, 80, 29);

        lerConsultas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lerConsultas.setText("Ler ");
        getContentPane().add(lerConsultas);
        lerConsultas.setBounds(200, 460, 70, 29);

        atualizarConsultas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        atualizarConsultas.setText("Atualizar ");
        getContentPane().add(atualizarConsultas);
        atualizarConsultas.setBounds(70, 490, 96, 29);

        cadastrarConsultas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadastrarConsultas.setText("Cadastrar ");
        cadastrarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarConsultas);
        cadastrarConsultas.setBounds(70, 460, 120, 29);

        listarConsultas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listarConsultas.setText("Listar");
        listarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(listarConsultas);
        listarConsultas.setBounds(290, 460, 80, 29);

        deletarEspecialidades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deletarEspecialidades.setText("Deletar");
        deletarEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarEspecialidadesActionPerformed(evt);
            }
        });
        getContentPane().add(deletarEspecialidades);
        deletarEspecialidades.setBounds(200, 610, 80, 29);

        lerEspecialidades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lerEspecialidades.setText("Ler ");
        getContentPane().add(lerEspecialidades);
        lerEspecialidades.setBounds(200, 580, 60, 29);

        cadastrarEspecialidades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadastrarEspecialidades.setText("Cadastrar ");
        cadastrarEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarEspecialidadesActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarEspecialidades);
        cadastrarEspecialidades.setBounds(70, 580, 130, 29);

        listarEspecialidades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listarEspecialidades.setText("Listar");
        listarEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarEspecialidadesActionPerformed(evt);
            }
        });
        getContentPane().add(listarEspecialidades);
        listarEspecialidades.setBounds(290, 580, 80, 29);

        atualizarEspecialidades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        atualizarEspecialidades.setText("Atualizar ");
        getContentPane().add(atualizarEspecialidades);
        atualizarEspecialidades.setBounds(70, 610, 96, 29);

        atualizarConvenios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        atualizarConvenios.setText("Atualizar ");
        getContentPane().add(atualizarConvenios);
        atualizarConvenios.setBounds(70, 720, 96, 29);

        lerConvenios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lerConvenios.setText("Ler ");
        getContentPane().add(lerConvenios);
        lerConvenios.setBounds(200, 690, 60, 29);

        cadastrarConvenios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadastrarConvenios.setText("Cadastrar ");
        cadastrarConvenios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarConveniosActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarConvenios);
        cadastrarConvenios.setBounds(70, 690, 120, 29);

        listarConvenios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listarConvenios.setText("Listar");
        listarConvenios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarConveniosActionPerformed(evt);
            }
        });
        getContentPane().add(listarConvenios);
        listarConvenios.setBounds(290, 690, 80, 29);

        deletarConvenios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deletarConvenios.setText("Deletar");
        deletarConvenios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarConveniosActionPerformed(evt);
            }
        });
        getContentPane().add(deletarConvenios);
        deletarConvenios.setBounds(200, 720, 80, 29);

        SALVAR.setBackground(new java.awt.Color(153, 255, 153));
        SALVAR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SALVAR.setText("SALVAR");
        SALVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALVARActionPerformed(evt);
            }
        });
        getContentPane().add(SALVAR);
        SALVAR.setBounds(60, 780, 170, 60);

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("LISTAR PERFIS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 780, 170, 60);

        BotãoVoltar.setBackground(new java.awt.Color(255, 153, 153));
        BotãoVoltar.setText("Voltar");
        BotãoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BotãoVoltar);
        BotãoVoltar.setBounds(390, 30, 90, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarFuncionariosActionPerformed

    private void deletarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarFuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletarFuncionariosActionPerformed

    private void listarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarFuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarFuncionariosActionPerformed

    private void NomePerfilTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomePerfilTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomePerfilTextFieldActionPerformed

    private void cadastrarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarPacientesActionPerformed

    private void listarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarPacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarPacientesActionPerformed

    private void deletarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarPacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletarPacientesActionPerformed

    private void deletarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletarConsultasActionPerformed

    private void cadastrarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarConsultasActionPerformed

    private void listarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarConsultasActionPerformed

    private void deletarEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarEspecialidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletarEspecialidadesActionPerformed

    private void cadastrarEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarEspecialidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarEspecialidadesActionPerformed

    private void listarEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarEspecialidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarEspecialidadesActionPerformed

    private void cadastrarConveniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarConveniosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarConveniosActionPerformed

    private void listarConveniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarConveniosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarConveniosActionPerformed

    private void deletarConveniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarConveniosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletarConveniosActionPerformed

    private void SALVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALVARActionPerformed
    try {
        // Capturar o nome do perfil
        String nomePerfil = NomePerfilTextField.getText();
        
        // Validar se o nome do perfil foi preenchido
        if (nomePerfil.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O nome do perfil é obrigatório.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Criar objeto Perfil com as permissões capturadas dos Checkboxes
        Perfil perfil = new Perfil(
            nomePerfil,
            cadastrarFuncionarios.isSelected(),
            lerFuncionarios.isSelected(),
            atualizarFuncionarios.isSelected(),
            deletarFuncionarios.isSelected(),
            listarFuncionarios.isSelected(),
            cadastrarPacientes.isSelected(),
            lerPacientes.isSelected(),
            atualizarPacientes.isSelected(),
            deletarPacientes.isSelected(),
            listarPacientes.isSelected(),
            cadastrarConsultas.isSelected(),
            lerConsultas.isSelected(),
            atualizarConsultas.isSelected(),
            deletarConsultas.isSelected(),
            listarConsultas.isSelected(),
            cadastrarEspecialidades.isSelected(),
            lerEspecialidades.isSelected(),
            atualizarEspecialidades.isSelected(),
            deletarEspecialidades.isSelected(),
            listarEspecialidades.isSelected(),
            cadastrarConvenios.isSelected(),
            lerConvenios.isSelected(),
            atualizarConvenios.isSelected(),
            deletarConvenios.isSelected(),
            listarConvenios.isSelected(),
            false, // Cadastrar prontuário
            false, // Ler prontuário
            false, // Atualizar prontuário
            false, // Deletar prontuário
            false  // Listar prontuário
        );

        // Salvar o perfil no banco de dados
        PerfilDAO perfilDAO = new PerfilDAO();
        perfilDAO.create(perfil);

        JOptionPane.showMessageDialog(this, "Perfil cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        // Limpar os campos da tela após salvar
        limparCampos();

    } catch (HeadlessException | SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao salvar o perfil: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
}

// Método para limpar os campos
private void limparCampos() {
    NomePerfilTextField.setText("");
    cadastrarFuncionarios.setSelected(false);
    lerFuncionarios.setSelected(false);
    atualizarFuncionarios.setSelected(false);
    deletarFuncionarios.setSelected(false);
    listarFuncionarios.setSelected(false);
    cadastrarPacientes.setSelected(false);
    lerPacientes.setSelected(false);
    atualizarPacientes.setSelected(false);
    deletarPacientes.setSelected(false);
    listarPacientes.setSelected(false);
    cadastrarConsultas.setSelected(false);
    lerConsultas.setSelected(false);
    atualizarConsultas.setSelected(false);
    deletarConsultas.setSelected(false);
    listarConsultas.setSelected(false);
    cadastrarEspecialidades.setSelected(false);
    lerEspecialidades.setSelected(false);
    atualizarEspecialidades.setSelected(false);
    deletarEspecialidades.setSelected(false);
    listarEspecialidades.setSelected(false);
    cadastrarConvenios.setSelected(false);
    lerConvenios.setSelected(false);
    atualizarConvenios.setSelected(false);
    deletarConvenios.setSelected(false);
    listarConvenios.setSelected(false);

    }//GEN-LAST:event_SALVARActionPerformed

    private void BotãoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoVoltarActionPerformed
        // TODO add your handling code here:
        TelaLobby telaLobby = new TelaLobby(); // Instancia a próxima tela
        telaLobby.setVisible(true); // Exibe a nova tela
        this.dispose(); // Fecha a tela atual (TelaLogin)
    }//GEN-LAST:event_BotãoVoltarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            // TODO add your handling code here:
        ListagemPerfil listagemPerfil = new ListagemPerfil(); // Instancia a próxima tela
        listagemPerfil.setVisible(true); // Exibe a nova tela
        this.dispose(); // Fecha a tela atual (TelaLogin)
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CadastrarPerfil().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotãoVoltar;
    private javax.swing.JTextField NomePerfilTextField;
    private javax.swing.JButton SALVAR;
    private javax.swing.JCheckBox atualizarConsultas;
    private javax.swing.JCheckBox atualizarConvenios;
    private javax.swing.JCheckBox atualizarEspecialidades;
    private javax.swing.JCheckBox atualizarFuncionarios;
    private javax.swing.JCheckBox atualizarPacientes;
    private javax.swing.JCheckBox cadastrarConsultas;
    private javax.swing.JCheckBox cadastrarConvenios;
    private javax.swing.JCheckBox cadastrarEspecialidades;
    private javax.swing.JCheckBox cadastrarFuncionarios;
    private javax.swing.JCheckBox cadastrarPacientes;
    private javax.swing.JCheckBox deletarConsultas;
    private javax.swing.JCheckBox deletarConvenios;
    private javax.swing.JCheckBox deletarEspecialidades;
    private javax.swing.JCheckBox deletarFuncionarios;
    private javax.swing.JCheckBox deletarPacientes;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox lerConsultas;
    private javax.swing.JCheckBox lerConvenios;
    private javax.swing.JCheckBox lerEspecialidades;
    private javax.swing.JCheckBox lerFuncionarios;
    private javax.swing.JCheckBox lerPacientes;
    private javax.swing.JCheckBox listarConsultas;
    private javax.swing.JCheckBox listarConvenios;
    private javax.swing.JCheckBox listarEspecialidades;
    private javax.swing.JCheckBox listarFuncionarios;
    private javax.swing.JCheckBox listarPacientes;
    // End of variables declaration//GEN-END:variables
}
