/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.administrativo.telas;

import br.edu.imepac.administrativo.daos.EspecialidadeDAO;
import br.edu.imepac.administrativo.entidades.Especialidade;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author elias
 */
public class CadastrarEspecialidade extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarEspecialidade
     */
    public CadastrarEspecialidade() {
        especialidadeDAO = new EspecialidadeDAO();

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        nomeField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoField = new javax.swing.JTextArea();
        cancelarButton = new javax.swing.JButton();
        salvarButton = new javax.swing.JButton();
        limparBotton = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        BotãoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1057, 399));
        setPreferredSize(new java.awt.Dimension(1057, 399));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de especialidades");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 20, 318, 40);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(6, 76, 1283, 3);

        nomeField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(nomeField);
        nomeField.setBounds(40, 130, 520, 50);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("Descrição");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 190, 76, 25);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 255));
        jLabel21.setText("Nome");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(40, 100, 60, 25);

        descricaoField.setColumns(20);
        descricaoField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        descricaoField.setRows(5);
        jScrollPane1.setViewportView(descricaoField);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 220, 520, 100);

        cancelarButton.setBackground(new java.awt.Color(255, 102, 102));
        cancelarButton.setText("CANCELAR");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarButton);
        cancelarButton.setBounds(610, 270, 240, 50);

        salvarButton.setBackground(new java.awt.Color(153, 255, 153));
        salvarButton.setText("SALVAR");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(salvarButton);
        salvarButton.setBounds(610, 130, 240, 50);

        limparBotton.setBackground(new java.awt.Color(255, 255, 153));
        limparBotton.setText("LIMPAR CAMPOS");
        limparBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparBottonActionPerformed(evt);
            }
        });
        getContentPane().add(limparBotton);
        limparBotton.setBounds(610, 200, 240, 50);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 102, 255));
        jLabel22.setText("Campo com as cores AZUL são obrigatórios.");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(130, 50, 280, 20);

        BotãoVoltar.setBackground(new java.awt.Color(255, 153, 153));
        BotãoVoltar.setText("Voltar");
        BotãoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BotãoVoltar);
        BotãoVoltar.setBounds(880, 20, 120, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
      if (descricaoField.getText().isEmpty() || nomeField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            Especialidade especialidade = new Especialidade(nomeField.getText(), descricaoField.getText());
          try {
              especialidadeDAO.create(especialidade);
          } catch (SQLException ex) {
              Logger.getLogger(CadastrarEspecialidade.class.getName()).log(Level.SEVERE, null, ex);
          }
            JOptionPane.showMessageDialog(null, "Especialidade cadastrada com sucesso.");

    ListagemEspecialidade listagemEspecialidade = new ListagemEspecialidade(); // Instancia a próxima tela
    listagemEspecialidade.setVisible(true); // Exibe a nova tela
    this.dispose(); // Fecha a tela atual
        }
    }//GEN-LAST:event_salvarButtonActionPerformed

    private void limparBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparBottonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limparBottonActionPerformed

    private void BotãoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoVoltarActionPerformed
        // TODO add your handling code here:
        TelaLobby telaLobby = new TelaLobby(); // Instancia a próxima tela
        telaLobby.setVisible(true); // Exibe a nova tela
        this.dispose(); // Fecha a tela atual (TelaLogin)
    }//GEN-LAST:event_BotãoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarEspecialidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarEspecialidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarEspecialidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarEspecialidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CadastrarEspecialidade().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotãoVoltar;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextArea descricaoField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton limparBotton;
    private javax.swing.JTextField nomeField;
    private javax.swing.JButton salvarButton;
    // End of variables declaration//GEN-END:variables
    private EspecialidadeDAO especialidadeDAO;
}
