/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.administrativo.telas;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.RenderingHints;
import javax.swing.border.AbstractBorder;

/**
 *
 * @author elias
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
UsuarioCampo.setBorder(new RoundedBorder(20)); // Define a borda arredondada
UsuarioCampo.setOpaque(false); // Campo transparente
UsuarioCampo.setBackground(new Color(0, 0, 0, 0)); // Fundo transparente
UsuarioCampo.setForeground(Color.WHITE); // Texto branco

SenhaCampo.setBorder(new RoundedBorder(20)); // Define a borda arredondada
SenhaCampo.setOpaque(false); // Campo transparente
SenhaCampo.setBackground(new Color(0, 0, 0, 0)); // Fundo transparente
SenhaCampo.setForeground(Color.WHITE); // Texto branco

BotaoAcessarLogin.setFocusPainted(false); // Remove o contorno ao clicar
BotaoAcessarLogin.setBorderPainted(false); // Remove a borda padrão
BotaoAcessarLogin.setContentAreaFilled(false); // Remove o fundo padrão
BotaoAcessarLogin.setOpaque(true); // Permite transparência
BotaoAcessarLogin.setBackground(new Color(120, 212, 255)); // Cor inicial
BotaoAcessarLogin.setForeground(new Color(28, 103, 152)); // Cor do texto inicial

// Adiciona efeito de hover e glow
BotaoAcessarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseEntered(java.awt.event.MouseEvent evt) {
        BotaoAcessarLogin.setBackground(new Color(255, 255, 255)); // Cor ao passar o mouse
        BotaoAcessarLogin.setForeground(new Color(28, 103, 152)); // Texto muda para branco
        BotaoAcessarLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 153, 255), 2)); // Glow azul
    }

    @Override
    public void mouseExited(java.awt.event.MouseEvent evt) {
        BotaoAcessarLogin.setBackground(new Color(120, 212, 255)); // Volta à cor original
        BotaoAcessarLogin.setForeground(new Color(28, 103, 152)); // Volta ao texto original
        BotaoAcessarLogin.setBorder(null); // Remove o glow
    }
});


            
            


        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsuarioCampo = new javax.swing.JTextField();
        SenhaCampo = new javax.swing.JPasswordField();
        UsuarioLabel = new javax.swing.JLabel();
        SenhaLabel = new javax.swing.JLabel();
        BotaoAcessarLogin = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LOGIN");
        setMaximumSize(new java.awt.Dimension(500, 700));
        setPreferredSize(new java.awt.Dimension(500, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        UsuarioCampo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        UsuarioCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioCampoActionPerformed(evt);
            }
        });
        getContentPane().add(UsuarioCampo);
        UsuarioCampo.setBounds(80, 290, 339, 45);

        SenhaCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaCampoActionPerformed(evt);
            }
        });
        getContentPane().add(SenhaCampo);
        SenhaCampo.setBounds(80, 380, 339, 45);

        UsuarioLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        UsuarioLabel.setForeground(new java.awt.Color(255, 255, 255));
        UsuarioLabel.setText("Usuário:");
        getContentPane().add(UsuarioLabel);
        UsuarioLabel.setBounds(80, 260, 90, 20);

        SenhaLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        SenhaLabel.setForeground(new java.awt.Color(255, 255, 255));
        SenhaLabel.setText("Senha:");
        getContentPane().add(SenhaLabel);
        SenhaLabel.setBounds(80, 350, 77, 20);

        BotaoAcessarLogin.setBackground(new java.awt.Color(120, 212, 255));
        BotaoAcessarLogin.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        BotaoAcessarLogin.setForeground(new java.awt.Color(28, 103, 152));
        BotaoAcessarLogin.setText("ACESSAR");
        BotaoAcessarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAcessarLoginActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoAcessarLogin);
        BotaoAcessarLogin.setBounds(80, 450, 340, 60);
        getContentPane().add(Imagem);
        Imagem.setBounds(0, 0, 500, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

public class RoundedBorder extends AbstractBorder {
    private int radius;
    
    @Override
    public Insets getBorderInsets(Component c) {
    return new Insets(10, 15, 10, 15); // Ajusta o espaço interno
}


    public RoundedBorder(int radius) {
        this.radius = radius;
    }

    @Override
    public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        g2.setColor(Color.WHITE); // Cor da borda
        g2.setStroke(new BasicStroke(2)); // Define a espessura da borda
        g2.drawRoundRect(x + 1, y + 1, width - 3, height - 3, radius, radius);
    }
}
    public Insets getBorderInsets(Component c) {
        return new Insets(10, 15, 10, 15); // Ajusta o espaço interno (padding)
    }

    public Insets getBorderInsets(Component c, Insets insets) {
        insets.left = 15;
        insets.right = 15;
        insets.top = 10;
        insets.bottom = 10;
        return insets;
    }


    private void SenhaCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaCampoActionPerformed

    private void BotaoAcessarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAcessarLoginActionPerformed
        // TODO add your handling code here:
        String usuario = UsuarioCampo.getText().trim(); 
    String senha = new String(SenhaCampo.getPassword()).trim();

    
    if (usuario.isEmpty() || senha.isEmpty()) { 
        
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Por favor, preencha todos os campos!", 
            "Aviso", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
        // Exemplo: redireciona para outra tela
        TelaLobby telaLobby = new TelaLobby(); // Instancia a próxima tela
        telaLobby.setVisible(true); // Exibe a nova tela
        this.dispose(); // Fecha a tela atual (TelaLogin)
        }
    }//GEN-LAST:event_BotaoAcessarLoginActionPerformed

    private void UsuarioCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioCampoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAcessarLogin;
    private javax.swing.JLabel Imagem;
    private javax.swing.JPasswordField SenhaCampo;
    private javax.swing.JLabel SenhaLabel;
    private javax.swing.JTextField UsuarioCampo;
    private javax.swing.JLabel UsuarioLabel;
    // End of variables declaration//GEN-END:variables
}


