/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.administrativo.telas;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author elias
 */
public class TelaLobby extends javax.swing.JFrame {

    /**
     * Creates new form TelaLobby
     */
    public TelaLobby() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListConvenios = new javax.swing.JButton();
        CadConvenios = new javax.swing.JButton();
        ListEspecialidades = new javax.swing.JButton();
        CadEspecialidades = new javax.swing.JButton();
        ListPerfis = new javax.swing.JButton();
        CadPerfis = new javax.swing.JButton();
        ListFuncionarios = new javax.swing.JButton();
        CadFuncionarios = new javax.swing.JButton();
        ListPacientes = new javax.swing.JButton();
        CadPacientes = new javax.swing.JButton();
        BotaoSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 1050));
        setPreferredSize(new java.awt.Dimension(1000, 1050));
        setResizable(false);
        getContentPane().setLayout(null);

        ListConvenios.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ListConvenios.setText("Listagem de convênios");
        ListConvenios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListConveniosActionPerformed(evt);
            }
        });
        getContentPane().add(ListConvenios);
        ListConvenios.setBounds(90, 100, 340, 52);

        CadConvenios.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CadConvenios.setText("Cadastrar convênios");
        CadConvenios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadConveniosActionPerformed(evt);
            }
        });
        getContentPane().add(CadConvenios);
        CadConvenios.setBounds(90, 170, 340, 52);

        ListEspecialidades.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ListEspecialidades.setText("Listagem de especialidades");
        ListEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListEspecialidadesActionPerformed(evt);
            }
        });
        getContentPane().add(ListEspecialidades);
        ListEspecialidades.setBounds(90, 260, 340, 52);

        CadEspecialidades.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CadEspecialidades.setText("Cadastrar especialidades");
        CadEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadEspecialidadesActionPerformed(evt);
            }
        });
        getContentPane().add(CadEspecialidades);
        CadEspecialidades.setBounds(90, 330, 340, 52);

        ListPerfis.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ListPerfis.setText("Listagem de perfis");
        ListPerfis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListPerfisActionPerformed(evt);
            }
        });
        getContentPane().add(ListPerfis);
        ListPerfis.setBounds(90, 420, 340, 52);

        CadPerfis.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CadPerfis.setText("Cadastrar perfis");
        CadPerfis.setToolTipText("");
        CadPerfis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadPerfisActionPerformed(evt);
            }
        });
        getContentPane().add(CadPerfis);
        CadPerfis.setBounds(90, 490, 340, 52);

        ListFuncionarios.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ListFuncionarios.setText("Listagem de funcionarios");
        ListFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListFuncionariosActionPerformed(evt);
            }
        });
        getContentPane().add(ListFuncionarios);
        ListFuncionarios.setBounds(90, 580, 340, 52);

        CadFuncionarios.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CadFuncionarios.setText("Cadastrar funcionarios");
        CadFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadFuncionariosActionPerformed(evt);
            }
        });
        getContentPane().add(CadFuncionarios);
        CadFuncionarios.setBounds(90, 650, 340, 52);

        ListPacientes.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ListPacientes.setText("Listagem Pacientes\n");
        ListPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(ListPacientes);
        ListPacientes.setBounds(90, 740, 340, 52);

        CadPacientes.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CadPacientes.setText("Cadastrar Pacientes");
        CadPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(CadPacientes);
        CadPacientes.setBounds(90, 810, 340, 52);

        BotaoSair.setBackground(new java.awt.Color(255, 0, 0));
        BotaoSair.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BotaoSair.setForeground(new java.awt.Color(255, 255, 255));
        BotaoSair.setText("Sair da conta");
        BotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoSair);
        BotaoSair.setBounds(90, 900, 340, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListConveniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListConveniosActionPerformed
        ListagemConvenio listagemConvenio = new ListagemConvenio(); // Instancia a próxima tela
        listagemConvenio.setVisible(true); // Exibe a nova tela
        this.dispose(); // Fecha a tela atual (TelaLogin)// TODO add your handling code here:
    }//GEN-LAST:event_ListConveniosActionPerformed

    private void CadConveniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadConveniosActionPerformed
        // TODO add your handling code here:
        CadastrarConvenio cadastrarConvenio = new CadastrarConvenio(); // Instancia a próxima tela
        cadastrarConvenio.setVisible(true); // Exibe a nova tela
        this.dispose(); // Fecha a tela atual (TelaLogin)// TODO add your handling code here:
    }//GEN-LAST:event_CadConveniosActionPerformed

    private void BotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairActionPerformed
        // TODO add your handling code here:
        TelaLogin telaLogin = new TelaLogin(); // Instancia a próxima tela
        telaLogin.setVisible(true); // Exibe a nova tela
        this.dispose(); // Fecha a tela atual (TelaLogin)
    }//GEN-LAST:event_BotaoSairActionPerformed

    private void ListEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListEspecialidadesActionPerformed
    ListagemEspecialidade listagemEspecialidade = new ListagemEspecialidade(); // Instancia a próxima tela
    listagemEspecialidade.setVisible(true); // Exibe a nova tela
    this.dispose(); // Fecha a tela atual
    }//GEN-LAST:event_ListEspecialidadesActionPerformed

    private void CadEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadEspecialidadesActionPerformed
        // TODO add your handling code here:
    CadastrarEspecialidade cadastrarEspecialidade = new CadastrarEspecialidade(); // Instancia a próxima tela
    cadastrarEspecialidade.setVisible(true); // Exibe a nova tela
    this.dispose(); // Fecha a tela atual

    }//GEN-LAST:event_CadEspecialidadesActionPerformed

    private void ListPerfisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListPerfisActionPerformed
     
        ListagemPerfil listagemPerfil = new ListagemPerfil(); // Instancia a próxima tela
        listagemPerfil.setVisible(true); // Exibe a nova tela
        this.dispose(); // Fecha a tela atual (TelaLogin)
    }//GEN-LAST:event_ListPerfisActionPerformed

    private void CadPerfisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadPerfisActionPerformed
        // TODO add your handling code here:
    CadastrarPerfil cadastrarPerfil = new CadastrarPerfil(); // Instancia a próxima tela
    cadastrarPerfil.setVisible(true); // Exibe a nova tela
    this.dispose(); // Fecha a tela atual
    }//GEN-LAST:event_CadPerfisActionPerformed

    private void ListFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListFuncionariosActionPerformed
     ListagemFuncionarios listagemFuncionarios = new ListagemFuncionarios(); // Instancia a próxima tela
    listagemFuncionarios.setVisible(true); // Exibe a nova tela
    this.dispose();
    }//GEN-LAST:event_ListFuncionariosActionPerformed

    private void CadFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadFuncionariosActionPerformed

        try {
            CadastrarFuncionarios cadastrarFuncionarios = new CadastrarFuncionarios(); // Instancia a próxima tela
            cadastrarFuncionarios.setVisible(true); // Exibe a nova tela
            this.dispose(); // Fecha a tela atual
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao abrir a tela de cadastro: " + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_CadFuncionariosActionPerformed

    private void ListPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListPacientesActionPerformed
     ListagemPaciente listagemPaciente = new ListagemPaciente(); // Instancia a próxima tela
    listagemPaciente.setVisible(true); // Exibe a nova tela
    this.dispose();
    }//GEN-LAST:event_ListPacientesActionPerformed

    private void CadPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadPacientesActionPerformed
    CadastrarPacientes cadastrarPacientes = new CadastrarPacientes(); // Instancia a próxima tela
    cadastrarPacientes.setVisible(true); // Exibe a nova tela
    this.dispose(); // Fecha a tela atual
    }//GEN-LAST:event_CadPacientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaLobby().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoSair;
    private javax.swing.JButton CadConvenios;
    private javax.swing.JButton CadEspecialidades;
    private javax.swing.JButton CadFuncionarios;
    private javax.swing.JButton CadPacientes;
    private javax.swing.JButton CadPerfis;
    private javax.swing.JButton ListConvenios;
    private javax.swing.JButton ListEspecialidades;
    private javax.swing.JButton ListFuncionarios;
    private javax.swing.JButton ListPacientes;
    private javax.swing.JButton ListPerfis;
    // End of variables declaration//GEN-END:variables
}
