/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.administrativo.telas.Paciente;

import br.edu.imepac.administrativo.daos.PacienteDao;
import br.edu.imepac.administrativo.entidades.Paciente;

import javax.swing.*;

/**
 *
 * @author ALUNO
 */
public class CadastrodePaciente2 extends javax.swing.JFrame {
    private javax.swing.JButton JBcan;
    private javax.swing.JButton JBsave;
    private javax.swing.JTextField JTbairro;
    private javax.swing.JTextField JTcom;
    private javax.swing.JTextField JTcontato;
    private javax.swing.JTextField JTcpf;
    private javax.swing.JTextField JTemail;
    private javax.swing.JTextField JTestado;
    private javax.swing.JTextField JTid;
    private javax.swing.JTextField JTidade;
    private javax.swing.JTextField JTnome;
    private javax.swing.JTextField JTnumero;
    private javax.swing.JTextField JTrua;
    private javax.swing.JTextField JTsexo;
    private javax.swing.JLabel Jbairro;
    private javax.swing.JLabel Jcom;
    private javax.swing.JLabel Jcontato;
    private javax.swing.JLabel Jcpf;
    private javax.swing.JLabel Jemail;
    private javax.swing.JLabel Jestado;
    private javax.swing.JLabel Jid;
    private javax.swing.JLabel Jidade;
    private javax.swing.JLabel Jnome;
    private javax.swing.JLabel Jnumero;
    private javax.swing.JLabel Jrua;
    private javax.swing.JLabel Jsexo;
    private javax.swing.JLabel jLabel1;

    /**
     * Creates new form CadastrodePaciente
     */
    public CadastrodePaciente2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel jLabel1 = new JLabel();
        Jidade = new javax.swing.JLabel();
        JTidade = new javax.swing.JTextField();
        Jnome = new javax.swing.JLabel();
        JTid = new javax.swing.JTextField();
        Jsexo = new javax.swing.JLabel();
        Jrua = new javax.swing.JLabel();
        Jcpf = new javax.swing.JLabel();
        Jnumero = new javax.swing.JLabel();
        Jcom = new javax.swing.JLabel();
        Jbairro = new javax.swing.JLabel();
        Jestado = new javax.swing.JLabel();
        Jcontato = new javax.swing.JLabel();
        Jemail = new javax.swing.JLabel();
        JTsexo = new javax.swing.JTextField();
        JTrua = new javax.swing.JTextField();
        JTcpf = new javax.swing.JTextField();
        JTbairro = new javax.swing.JTextField();
        JTnumero = new javax.swing.JTextField();
        JTcom = new javax.swing.JTextField();
        JTestado = new javax.swing.JTextField();
        JTcontato = new javax.swing.JTextField();
        JTemail = new javax.swing.JTextField();
        JBsave = new javax.swing.JButton();
        JBcan = new javax.swing.JButton();
        Jid = new javax.swing.JLabel();
        JTnome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Atualização de Paciente");

        Jidade.setText("Idade");

        JTidade.setBackground(new java.awt.Color(204, 204, 204));
        JTidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTidadeActionPerformed(evt);
            }
        });

        Jnome.setText("Nome");

        JTid.setBackground(new java.awt.Color(204, 204, 204));
        JTid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTidActionPerformed(evt);
            }
        });

        Jsexo.setText("Sexo");

        Jrua.setText("Rua");

        Jcpf.setText("CPF");

        Jnumero.setText("Número");

        Jcom.setText("Complemento");

        Jbairro.setText("Bairro");

        Jestado.setText("Estado");

        Jcontato.setText("Contato");

        Jemail.setText("Email");

        JTsexo.setBackground(new java.awt.Color(204, 204, 204));
        JTsexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTsexoActionPerformed(evt);
            }
        });

        JTrua.setBackground(new java.awt.Color(204, 204, 204));
        JTrua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTruaActionPerformed(evt);
            }
        });

        JTcpf.setBackground(new java.awt.Color(204, 204, 204));
        JTcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTcpfActionPerformed(evt);
            }
        });

        JTbairro.setBackground(new java.awt.Color(204, 204, 204));
        JTbairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTbairroActionPerformed(evt);
            }
        });

        JTnumero.setBackground(new java.awt.Color(204, 204, 204));
        JTnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTnumeroActionPerformed(evt);
            }
        });

        JTcom.setBackground(new java.awt.Color(204, 204, 204));
        JTcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTcomActionPerformed(evt);
            }
        });

        JTestado.setBackground(new java.awt.Color(204, 204, 204));
        JTestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTestadoActionPerformed(evt);
            }
        });

        JTcontato.setBackground(new java.awt.Color(204, 204, 204));
        JTcontato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTcontatoActionPerformed(evt);
            }
        });

        JTemail.setBackground(new java.awt.Color(204, 204, 204));
        JTemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTemailActionPerformed(evt);
            }
        });

        JBsave.setText("Salvar");
        JBsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsaveActionPerformed(evt);
            }
        });

        JBcan.setText("Cancelar");
        JBcan.setToolTipText("");
        JBcan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcanActionPerformed(evt);
            }
        });

        Jid.setText("ID");



        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Jnome))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTidade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(Jsexo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Jcpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTnome)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Jrua)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JTrua, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Jnumero)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JTnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Jcom)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JTcom))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Jbairro)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JTbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Jestado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JTestado)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jcontato)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTcontato, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBsave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBcan))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jemail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTemail, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(75, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jid)
                    .addComponent(JTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jnome)
                    .addComponent(JTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jidade)
                    .addComponent(JTidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jsexo)
                    .addComponent(JTsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jcpf)
                    .addComponent(JTcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jrua)
                    .addComponent(JTrua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jnumero)
                    .addComponent(JTnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jcom, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jbairro)
                    .addComponent(JTbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jestado)
                    .addComponent(JTestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jcontato)
                    .addComponent(JTcontato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jemail)
                    .addComponent(JTemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBsave)
                    .addComponent(JBcan))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void JTnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTnomeActionPerformed

    private void JTidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTidadeActionPerformed

    private void JTidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTidActionPerformed

    private void JTsexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTsexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTsexoActionPerformed

    private void JTruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTruaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTruaActionPerformed

    private void JTcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTcpfActionPerformed

    private void JTbairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTbairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTbairroActionPerformed

    private void JTnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTnumeroActionPerformed

    private void JTcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTcomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTcomActionPerformed

    private void JTestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTestadoActionPerformed

    private void JTcontatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTcontatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTcontatoActionPerformed

    private void JTemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTemailActionPerformed

    private void JBsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsaveActionPerformed

    try {
       // Criar o objeto paciente com os dados atualizados
        Paciente paciente = new Paciente();
        paciente.setId(Integer.parseInt(JTid.getText()));
        paciente.setNome(JTnome.getText());
        paciente.setidade(Integer.parseInt(JTidade.getText()));
        paciente.setSexo(JTsexo.getText());
        paciente.setCpf(JTcpf.getText());
        paciente.setRua(JTrua.getText());
        paciente.setNumero(Integer.parseInt(JTnumero.getText()));
        paciente.setComplemento(JTcom.getText());
        paciente.setBairro(JTbairro.getText());
        paciente.setEstado(JTestado.getText());
        paciente.setContato(JTcontato.getText());
        paciente.setEmail(JTemail.getText());
       // paciente.setDataNascimento(txtDataNascimento.getText());

        // Atualizar no banco de dados
        PacienteDao pacienteDao = new PacienteDao();
        pacienteDao.atualizar(paciente);

        JOptionPane.showMessageDialog(this, "Paciente atualizado com sucesso!");
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao atualizar paciente: " + e.getMessage());
    }
   }
  };

    private void JBcanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcanActionPerformed
    this.dispose(); // Fecha a tela de atualização
    }



    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      //  try {
        //    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
       //         if ("Nimbus".equals(info.getName())) {
      //              javax.swing.UIManager.setLookAndFeel(info.getClassName());
       //             break;
      //          }
    //        }
     //   } catch (ClassNotFoundException ex) {
    //        java.util.logging.Logger.getLogger(CadastrodePaciente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //    } catch (InstantiationException ex) {
    //        java.util.logging.Logger.getLogger(CadastrodePaciente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //    } catch (IllegalAccessException ex) {
   //         java.util.logging.Logger.getLogger(CadastrodePaciente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     //   } catch (javax.swing.UnsupportedLookAndFeelException ex) {
   //         java.util.logging.Logger.getLogger(CadastrodePaciente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
   //     }
    //    //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    //    java.awt.EventQueue.invokeLater(new Runnable() {
    //        public void run() {
   //             new CadastrodePaciente2().setVisible(true);
  //          }
   //     });
  //  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
  //  private javax.swing.JButton JBcan;
  //  private javax.swing.JButton JBsave;
  //  private javax.swing.JTextField JTbairro;
//    private javax.swing.JTextField JTcom;
  //  private javax.swing.JTextField JTcontato;
  //  private javax.swing.JTextField JTcpf;
  //  private javax.swing.JTextField JTemail;
  //  private javax.swing.JTextField JTestado;
 //   private javax.swing.JTextField JTid;
    //private javax.swing.JTextField JTidade;
  //  private javax.swing.JTextField JTnome;
  //  private javax.swing.JTextField JTnumero;
  //  private javax.swing.JTextField JTrua;
  //  private javax.swing.JTextField JTsexo;
  //  private javax.swing.JLabel Jbairro;
   // private javax.swing.JLabel Jcom;
   // private javax.swing.JLabel Jcontato;
  //  private javax.swing.JLabel Jcpf;
  //  private javax.swing.JLabel Jemail;
 //   private javax.swing.JLabel Jestado;
 //   private javax.swing.JLabel Jid;
  //  private javax.swing.JLabel Jidade;
  //  private javax.swing.JLabel Jnome;
  //  private javax.swing.JLabel Jnumero;
 //   private javax.swing.JLabel Jrua;
//    private javax.swing.JLabel Jsexo;
  //  private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

