/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.administrativo.telas.Paciente;

import br.edu.imepac.administrativo.daos.PacienteDao;
import br.edu.imepac.administrativo.entidades.Paciente;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Date;

/**
 *
 * @author ALUNO
 */
public class CadastrodePaciente extends javax.swing.JFrame {

    private JLabel Jti;
    private JLabel Jidade;
    private JTextField JTidade;
    private JLabel Jname;
    private JTextField JTnome;
    private JLabel Jsexo;
    private JLabel Jrua;
    private JLabel Jcpf;
    private JLabel Jnumero;
    private JLabel Jcom;
    private JLabel Jbairro;
    private JLabel Jestado;
    private JLabel Jcontato;
    private JLabel Jemail;
    private JLabel JdataN;
    private JTextField JTsexo;
    private JTextField JTrua;
    private JTextField JTcpf;
    private JTextField JTnumero;
    private JTextField JTbairro;
    private JTextField JTcom;
    private JTextField JTestado;
    private JTextField JTcontato;
    private JTextField JTemail;
    private JButton jsaval;
    private JButton jcan;
    private JTextField JTdadaN;

    /**
     * Creates new form CadastrodePaciente
     */
    public CadastrodePaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jti = new javax.swing.JLabel();
        Jidade = new javax.swing.JLabel();
        JTidade = new javax.swing.JTextField();
        Jname = new javax.swing.JLabel();
        JTnome = new javax.swing.JTextField();
        Jsexo = new javax.swing.JLabel();
        Jrua = new javax.swing.JLabel();
        Jcpf = new javax.swing.JLabel();
        Jnumero = new javax.swing.JLabel();
        Jcom = new javax.swing.JLabel();
        Jbairro = new javax.swing.JLabel();
        Jestado = new javax.swing.JLabel();
        Jcontato = new javax.swing.JLabel();
        Jemail = new javax.swing.JLabel();
        JTsexo = new javax.swing.JTextField();
        JTrua = new javax.swing.JTextField();
        JTcpf = new javax.swing.JTextField();
        JTbairro = new javax.swing.JTextField();
        JTnumero = new javax.swing.JTextField();
        JTcom = new javax.swing.JTextField();
        JTestado = new javax.swing.JTextField();
        JTcontato = new javax.swing.JTextField();
        JTemail = new javax.swing.JTextField();
        JBsaval = new javax.swing.JButton();
        JBcan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jti.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Jti.setText("Cadastro de Paciente ");

        Jidade.setText("Idade");

        JTidade.setBackground(new java.awt.Color(204, 204, 204));
        JTidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTidadeActionPerformed(evt);
            }
        });

        Jname.setText("Nome");

        JTnome.setBackground(new java.awt.Color(204, 204, 204));
        JTnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTnomeActionPerformed(evt);
            }
        });

        Jsexo.setText("Sexo");

        Jrua.setText("Rua");

        Jcpf.setText("CPF");

        Jnumero.setText("N�mero");

        Jcom.setText("Complemento");

        Jbairro.setText("Bairro");

        Jestado.setText("Estado");

        Jcontato.setText("Contato");

        Jemail.setText("Email");

        JTsexo.setBackground(new java.awt.Color(204, 204, 204));
        JTsexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTsexoActionPerformed(evt);
            }
        });

        JTrua.setBackground(new java.awt.Color(204, 204, 204));
        JTrua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTruaActionPerformed(evt);
            }
        });

        JTcpf.setBackground(new java.awt.Color(204, 204, 204));
        JTcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTcpfActionPerformed(evt);
            }
        });

        JTbairro.setBackground(new java.awt.Color(204, 204, 204));
        JTbairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTbairroActionPerformed(evt);
            }
        });

        JTnumero.setBackground(new java.awt.Color(204, 204, 204));
        JTnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTnumeroActionPerformed(evt);
            }
        });

        JTcom.setBackground(new java.awt.Color(204, 204, 204));
        JTcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTcomActionPerformed(evt);
            }
        });

        JTestado.setBackground(new java.awt.Color(204, 204, 204));
        JTestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTestadoActionPerformed(evt);
            }
        });

        JTcontato.setBackground(new java.awt.Color(204, 204, 204));
        JTcontato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTcontatoActionPerformed(evt);
            }
        });

        JTemail.setBackground(new java.awt.Color(204, 204, 204));
        JTemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTemailActionPerformed(evt);
            }
        });

        JBsaval.setText("Salvar");
        JBsaval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsavalActionPerformed(evt);
            }
        });

        JBcan.setText("Cancelar");
        JBcan.setToolTipText("");
        JBcan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jestado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTestado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jcontato))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Jrua)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JTrua)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Jnumero)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JTnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Jidade)
                                .addComponent(Jname))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JTidade, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Jsexo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JTsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Jcpf)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JTcpf))
                                .addComponent(JTnome, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jemail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTemail, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JTcontato, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Jcom)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JTcom, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jbairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBsaval)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBcan)))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Jti)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jti)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jname)
                    .addComponent(JTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jidade)
                    .addComponent(JTidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jsexo)
                    .addComponent(JTsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jcpf)
                    .addComponent(JTcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jrua)
                    .addComponent(JTrua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jnumero)
                    .addComponent(JTnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jcom, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jbairro)
                    .addComponent(JTbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jestado)
                    .addComponent(JTestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jcontato)
                    .addComponent(JTcontato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jemail)
                    .addComponent(JTemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBsaval)
                    .addComponent(JBcan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  //  private void JTdadaNActionPerformed(ActionEvent evt) {//GEN-FIRST:event_JTdataNActionPerformed
    //    // TODO add your handling code here:
   // }//GEN-LAST:event_JTdataNActionPerformed

    private void JTidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTidadeActionPerformed

    private void JTnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTnomeActionPerformed

    private void JTsexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTsexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTsexoActionPerformed

    private void JTruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTruaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTruaActionPerformed

    private void JTcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTcpfActionPerformed

    private void JTbairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTbairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTbairroActionPerformed

    private void JTnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTnumeroActionPerformed

    private void JTcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTcomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTcomActionPerformed

    private void JTestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTestadoActionPerformed

    private void JTcontatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTcontatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTcontatoActionPerformed

    private void JTemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTemailActionPerformed
    private void JTdataNActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }   
    private void JBsavalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsavalActionPerformed
 
    // Criar uma instância de Paciente
    Paciente paciente = new Paciente();
    //
    // Preencher os atributos do paciente com os valores dos campos
    paciente.setNome(JTnome.getText());
    paciente.setidade(Integer.parseInt(JTidade.getText()));
    paciente.setSexo(JTsexo.getText());
    paciente.setCpf(JTcpf.getText());
    paciente.setRua(JTrua.getText());
    paciente.setNumero(Integer.parseInt(JTnumero.getText()));
    paciente.setComplemento(JTcom.getText());
    paciente.setBairro(JTbairro.getText());
    paciente.setEstado(JTestado.getText());
    paciente.setContato(JTcontato.getText());
    paciente.setEmail(JTemail.getText());
    paciente.setDataNascimento(Date.valueOf(JTdadaN.getText()));
    
   
    try {
        PacienteDao pacienteDao = new PacienteDao();
        pacienteDao.save(paciente);
        JOptionPane.showMessageDialog(this, "Paciente salvo com sucesso!");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Erro ao salvar o paciente: " + ex.getMessage());
    }
}

        // TODO add your handling code here:
  // }//GEN-LAST:event_JBsavalActionPerformed

    private void jcanActionPerformed(java.awt.event.ActionEvent evt) {                                     

    // Limpar os campos do formulário
    JTnome.setText("");
    JTidade.setText("");
    JTsexo.setText("");
    JTcpf.setText("");
    JTrua.setText("");
    JTnumero.setText("");
    JTcom.setText("");
    JTbairro.setText("");
    JTestado.setText("");
    JTcontato.setText("");
    JTemail.setText("");
    //JTdataN.setText("");
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrodePaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrodePaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrodePaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrodePaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrodePaciente().setVisible(true);
            }
        });
    }
}                                    





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBcan;
    private javax.swing.JButton JBsaval;
    private javax.swing.JTextField JTbairro;
    private javax.swing.JTextField JTcom;
    private javax.swing.JTextField JTcontato;
    private javax.swing.JTextField JTcpf;
    private javax.swing.JTextField JTemail;
    private javax.swing.JTextField JTestado;
    private javax.swing.JTextField JTidade;
    private javax.swing.JTextField JTnome;
    private javax.swing.JTextField JTnumero;
    private javax.swing.JTextField JTrua;
    private javax.swing.JTextField JTsexo;
    private javax.swing.JLabel Jbairro;
    private javax.swing.JLabel Jcom;
    private javax.swing.JLabel Jcontato;
    private javax.swing.JLabel Jcpf;
    private javax.swing.JLabel Jemail;
    private javax.swing.JLabel Jestado;
    private javax.swing.JLabel Jidade;
    private javax.swing.JLabel Jname;
    private javax.swing.JLabel Jnumero;
    private javax.swing.JLabel Jrua;
    private javax.swing.JLabel Jsexo;
    private javax.swing.JLabel Jti;
    // End of variables declaration//GEN-END:variables

