package br.edu.imepac.agendamento.telas;

import br.edu.imepac.administrativo.daos.ProntuarioDAO;
import br.edu.imepac.administrativo.entidades.Prontuario;
import br.edu.imepac.administrativo.telas.TelaLobby;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.util.List;

public class CriarProntuario extends javax.swing.JFrame {

    private ProntuarioDAO prontuarioDAO;

    public CriarProntuario() {
        prontuarioDAO = new ProntuarioDAO();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        receiruariojTextField1 = new javax.swing.JTextField();
        ObservacoesjTextField2 = new javax.swing.JTextField();
        ExamesjTextField3 = new javax.swing.JTextField();
        SalvarjButton1 = new javax.swing.JButton();
        ListarjButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        BotãoVoltar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(796, 524));
        setMinimumSize(new java.awt.Dimension(796, 524));
        setPreferredSize(new java.awt.Dimension(796, 524));
        getContentPane().setLayout(null);
        getContentPane().add(receiruariojTextField1);
        receiruariojTextField1.setBounds(70, 140, 410, 80);
        getContentPane().add(ObservacoesjTextField2);
        ObservacoesjTextField2.setBounds(70, 360, 410, 80);
        getContentPane().add(ExamesjTextField3);
        ExamesjTextField3.setBounds(70, 260, 410, 50);

        SalvarjButton1.setBackground(new java.awt.Color(153, 204, 255));
        SalvarjButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SalvarjButton1.setText("Salvar");
        SalvarjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarjButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(SalvarjButton1);
        SalvarjButton1.setBounds(540, 140, 200, 50);

        ListarjButton2.setBackground(new java.awt.Color(255, 255, 153));
        ListarjButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ListarjButton2.setText("Listar");
        ListarjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarjButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(ListarjButton2);
        ListarjButton2.setBounds(540, 210, 200, 50);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("FAZER PRONTUARIO");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(70, 30, 250, 32);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(-330, 80, 1250, 10);

        BotãoVoltar.setBackground(new java.awt.Color(255, 153, 153));
        BotãoVoltar.setText("Voltar");
        BotãoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BotãoVoltar);
        BotãoVoltar.setBounds(580, 30, 170, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("OBSERVAÇÕES");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 330, 100, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setText("RECEITUARIO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 110, 88, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setText("EXAMES");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 230, 51, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarjButton1ActionPerformed
         try {
        String receituario = receiruariojTextField1.getText().trim();
        String exames = ExamesjTextField3.getText().trim();
        String observacoes = ObservacoesjTextField2.getText().trim();

        if (receituario.isEmpty() || exames.isEmpty() || observacoes.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Prontuario prontuario = new Prontuario(receituario, exames, observacoes);
        ProntuarioDAO dao = new ProntuarioDAO();
        dao.create(prontuario);

        JOptionPane.showMessageDialog(this, "Prontuário salvo com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        limparCampos();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao salvar: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_SalvarjButton1ActionPerformed

    private void ListarjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarjButton2ActionPerformed
      new ListarProntuario().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_ListarjButton2ActionPerformed

    private void BotãoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoVoltarActionPerformed
        // TODO add your handling code here:
        TelaLobby telaLobby = new TelaLobby(); // Instancia a próxima tela
        telaLobby.setVisible(true); // Exibe a nova tela
        this.dispose(); // Fecha a tela atual (TelaLogin)
    }//GEN-LAST:event_BotãoVoltarActionPerformed

    private void limparCampos() {
    receiruariojTextField1.setText("");
    ExamesjTextField3.setText("");
    ObservacoesjTextField2.setText("");
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarProntuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotãoVoltar;
    private javax.swing.JTextField ExamesjTextField3;
    private javax.swing.JButton ListarjButton2;
    private javax.swing.JTextField ObservacoesjTextField2;
    private javax.swing.JButton SalvarjButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField receiruariojTextField1;
    // End of variables declaration//GEN-END:variables
}
